#!/bin/tcsh

#SBATCH	--exclude=compute-0-17,compute-0-18,compute-0-27,compute-0-40,compute-0-41,compute-0-42,compute-0-49,compute-0-44,compute-0-61,compute-0-64,compute-0-28
#SBATCH --account=local
#SBATCH --array=1-20
#SBATCH --cpus-per-task 1
#SBATCH --mem-per-cpu 2G
#SBATCH --ntasks-per-node=1

./$script ${SLURM_ARRAY_TASK_ID} $plist $dplist $demmask $id

